name: Release to gh pages
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build the Application
    outputs:
      target_run_id: ${{ github.run_id }}
    steps:
      - name: Checking out code
        uses: actions/checkout@v4
      - name: Installing Node.js v20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Cache - node modules
        uses: actions/cache@v4
        id: node-modules-cache
        with:
          path: ./node_modules
          key: ${{ runner.os }}-node-modules-cache-${{ hashFiles('**/yarn.lock') }}
      - if: ${{ steps.node-modules-cache.outputs.cache-hit != 'true'}}
        name: Installing dependencies
        working-directory: ./
        run: yarn install
      - name: Building project
        working-directory: ./
        run: yarn build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          name: app-build
          path: ./build

  deploy:
    needs: build
    permissions:
      id-token: write
      pages: write
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
        with:
          artifact_name: "app-build"
